version: '3.6'

# Better setup for secrets is needed: https://github.com/drone/drone/issues/2223

services:
  drone:
    image: drone/drone:1.0.0-rc.1
    ports:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - drone-data:/data
    # https://readme.drone.io/reference/server/
    environment:
      DRONE_SERVER_HOST: drone.YOURDOMAIN.com
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: "false"
      DRONE_RUNNER_CAPACITY: 2
      DRONE_TLS_AUTOCERT: "false"
      # filter by user or organizations
      DRONE_USER_FILTER: MYUSER,MYORGANIZATION
      # Set the ADMIN user, this user can change sensitive settings in Drone UI and CLI
      DRONE_USER_CREATE: username:GITLAB_USERNAME,machine:false,admin:true
      # https://readme.drone.io/intro/gitlab/
      DRONE_GITLAB_CLIENT_ID: DRONE_GITLAB_CLIENT_ID
      DRONE_GITLAB_CLIENT_SECRET: DRONE_GITLAB_CLIENT_SECRET
      # https://readme.drone.io/install/server/storage/encryption/
      DRONE_DATABASE_SECRET: DRONE_DATABASE_SECRET
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider http://localhost:80 || exit 1"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  drone-data: {}
