version: '3.6'

services:
  caddy:
    image: douglasmiranda/caddy
    volumes:
      - caddy:/home/caddy/.caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy: {}
