version: "3"

services:
  netdata:
    # image: douglasmiranda/netdata
    build: .
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
